-- ───────────────────────────────────────────────
--  1. Create members table (if it doesn't exist)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.members (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id        UUID  REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  wallet_points  INT   NOT NULL DEFAULT 40,   -- 40 pts = 20 h quiet time / calendar month
  red_points_week INT  NOT NULL DEFAULT 0,    -- tracks weekend pts this week
  red_cap_week   INT   NOT NULL DEFAULT 6,    -- 6 pts = 3 h red time / week
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);

-- ───────────────────────────────────────────────
--  2. Create a point ledger (audits, UI)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.point_ledger (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id      UUID  REFERENCES public.members(auth_id) ON DELETE CASCADE,
  delta          INT   NOT NULL,          -- + or –
  reason         TEXT  NOT NULL,          -- reserve | cancel_refund | monthly_refresh | …
  ref_booking_id UUID,                    -- FK → bookings.id (nullable)
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- ───────────────────────────────────────────────
--  3. Add band & cost columns to existing bookings table
-- ───────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name='bookings' AND column_name='band'
  ) THEN
    ALTER TABLE public.bookings
      ADD COLUMN band TEXT NOT NULL DEFAULT 'green',   -- green | yellow | red
      ADD COLUMN points_cost INT NOT NULL DEFAULT 1;   -- 1–3 depending on band
  END IF;
END $$;

-- ───────────────────────────────────────────────
--  4. Create indexes for performance
-- ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_members_auth_id ON public.members(auth_id);
CREATE INDEX IF NOT EXISTS idx_point_ledger_member_id ON public.point_ledger(member_id);
CREATE INDEX IF NOT EXISTS idx_point_ledger_created_at ON public.point_ledger(created_at);

-- ───────────────────────────────────────────────
--  5. Enable RLS on new tables
-- ───────────────────────────────────────────────
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.point_ledger ENABLE ROW LEVEL SECURITY;

-- ───────────────────────────────────────────────
--  6. Create RLS policies
-- ───────────────────────────────────────────────
-- Members can view and update their own record
CREATE POLICY "Users can view their own member record" ON public.members
  FOR SELECT USING (auth.uid() = auth_id);

CREATE POLICY "Users can update their own member record" ON public.members
  FOR UPDATE USING (auth.uid() = auth_id);

CREATE POLICY "Users can insert their own member record" ON public.members
  FOR INSERT WITH CHECK (auth.uid() = auth_id);

-- Users can view their own point ledger entries
CREATE POLICY "Users can view their own point ledger" ON public.point_ledger
  FOR SELECT USING (auth.uid() = member_id);

-- ───────────────────────────────────────────────
--  7. Create function to automatically create member record
-- ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.members (auth_id)
  VALUES (new.id)
  ON CONFLICT (auth_id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ───────────────────────────────────────────────
--  8. Create trigger to auto-create member records
-- ───────────────────────────────────────────────
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ───────────────────────────────────────────────
--  9. Create existing users as members (if any)
-- ───────────────────────────────────────────────
INSERT INTO public.members (auth_id)
SELECT id FROM auth.users
ON CONFLICT (auth_id) DO NOTHING;

-- ───────────────────────────────────────────────
--  10. Monthly refresh cron job
-- ───────────────────────────────────────────────
WITH upd AS (
  UPDATE public.members
  SET    wallet_points = 40
  RETURNING auth_id
)
INSERT INTO public.point_ledger (member_id, delta, reason)
SELECT auth_id, 40, 'monthly_refresh' FROM upd;
